// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLBH.Models;

#nullable disable

namespace QLBH.Migrations
{
    [DbContext(typeof(QlbandoanContext))]
    partial class QlbandoanContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLBH.Models.Chitiethoadon", b =>
                {
                    b.Property<int>("SoHdb")
                        .HasColumnType("int")
                        .HasColumnName("SoHDB");

                    b.Property<int>("MaChiTietSp")
                        .HasColumnType("int")
                        .HasColumnName("MaChiTietSP");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("SoHdb", "MaChiTietSp");

                    b.HasIndex("MaChiTietSp");

                    b.ToTable("CHITIETHOADON", (string)null);
                });

            modelBuilder.Entity("QLBH.Models.Chitietmonan", b =>
                {
                    b.Property<int>("MaChiTietSp")
                        .HasColumnType("int")
                        .HasColumnName("MaChiTietSP");

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("char(100)")
                        .IsFixedLength();

                    b.Property<int?>("MaMonAn")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal?>("ThanhTien")
                        .HasColumnType("money");

                    b.HasKey("MaChiTietSp");

                    b.HasIndex("MaMonAn");

                    b.ToTable("CHITIETMONAN", (string)null);
                });

            modelBuilder.Entity("QLBH.Models.Hoadonban", b =>
                {
                    b.Property<int>("SoHdb")
                        .HasColumnType("int")
                        .HasColumnName("SoHDB");

                    b.Property<int?>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<DateTime?>("NgayDatHang")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThaiTt")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TrangThaiTT");

                    b.HasKey("SoHdb");

                    b.HasIndex("MaKh");

                    b.ToTable("HOADONBAN", (string)null);
                });

            modelBuilder.Entity("QLBH.Models.Khachhang", b =>
                {
                    b.Property<int>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenKh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenKH");

                    b.HasKey("MaKh");

                    b.ToTable("KHACHHANG", (string)null);
                });

            modelBuilder.Entity("QLBH.Models.Loaimonan", b =>
                {
                    b.Property<int>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("TenLoai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoai");

                    b.ToTable("LOAIMONAN", (string)null);
                });

            modelBuilder.Entity("QLBH.Models.Monan", b =>
                {
                    b.Property<int>("MaMonAn")
                        .HasColumnType("int");

                    b.Property<string>("Anh")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("char(100)")
                        .IsFixedLength();

                    b.Property<decimal?>("DonGiaBan")
                        .HasColumnType("money");

                    b.Property<int?>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("TenHh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenHH");

                    b.HasKey("MaMonAn");

                    b.HasIndex("MaLoai");

                    b.ToTable("MONAN", (string)null);
                });

            modelBuilder.Entity("QLBH.Models.Nguoidung", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<string>("Loai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TaiKhoan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("NGUOIDUNG", (string)null);
                });

            modelBuilder.Entity("QLBH.Models.Chitiethoadon", b =>
                {
                    b.HasOne("QLBH.Models.Chitietmonan", "MaChiTietSpNavigation")
                        .WithMany("Chitiethoadons")
                        .HasForeignKey("MaChiTietSp")
                        .IsRequired()
                        .HasConstraintName("FK_CHITIETHOADON_CHITIETMONAN");

                    b.HasOne("QLBH.Models.Hoadonban", "SoHdbNavigation")
                        .WithMany("Chitiethoadons")
                        .HasForeignKey("SoHdb")
                        .IsRequired()
                        .HasConstraintName("FK_CHITIETHOADON_HOADONBAN");

                    b.Navigation("MaChiTietSpNavigation");

                    b.Navigation("SoHdbNavigation");
                });

            modelBuilder.Entity("QLBH.Models.Chitietmonan", b =>
                {
                    b.HasOne("QLBH.Models.Monan", "MaMonAnNavigation")
                        .WithMany("Chitietmonans")
                        .HasForeignKey("MaMonAn")
                        .HasConstraintName("FK_CHITIETMONAN_MONAN");

                    b.Navigation("MaMonAnNavigation");
                });

            modelBuilder.Entity("QLBH.Models.Hoadonban", b =>
                {
                    b.HasOne("QLBH.Models.Khachhang", "MaKhNavigation")
                        .WithMany("Hoadonbans")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK_HOADONBAN_KHACHHANG");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("QLBH.Models.Monan", b =>
                {
                    b.HasOne("QLBH.Models.Loaimonan", "MaLoaiNavigation")
                        .WithMany("Monans")
                        .HasForeignKey("MaLoai")
                        .HasConstraintName("FK_MONAN_LOAIMONAN");

                    b.Navigation("MaLoaiNavigation");
                });

            modelBuilder.Entity("QLBH.Models.Chitietmonan", b =>
                {
                    b.Navigation("Chitiethoadons");
                });

            modelBuilder.Entity("QLBH.Models.Hoadonban", b =>
                {
                    b.Navigation("Chitiethoadons");
                });

            modelBuilder.Entity("QLBH.Models.Khachhang", b =>
                {
                    b.Navigation("Hoadonbans");
                });

            modelBuilder.Entity("QLBH.Models.Loaimonan", b =>
                {
                    b.Navigation("Monans");
                });

            modelBuilder.Entity("QLBH.Models.Monan", b =>
                {
                    b.Navigation("Chitietmonans");
                });
#pragma warning restore 612, 618
        }
    }
}
